### ISSUE TITLE
Create UI for data display

### ISSUE THREAD

**Issue by SiddharthMantri** [SiddharthMantri/covid-graphql#2]
I'd like to create a UI for the data, especially the time series one to be able to make sense of `exponential` growth.

**Comment by sam-cross** [comment]
[This](https://alligator.io/react/server-side-rendering/) could be of interest regarding SSR on the UI. Seems fairly simple, just a lot of added dependencies.

**Comment by SiddharthMantri** [comment]
Completed SSR
